config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  root 'browse#main'
  get 'browse/acerca_de'

  namespace :admin do
    resources :encuestas
    resources :categorias
    post 'encuestas/votar'
    get 'encuestas/:id/resultados' => 'encuestas#resultados'
  end

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base
	has_many :encuestas
end

app/models/encuesta.rb
class Encuesta < ActiveRecord::Base
	has_many :opciones
	belongs_to :categoria
	accepts_nested_attributes_for :opciones, :reject_if => :all_blank, :allow_destroy => true

	def self.populares
		limit(4)
	end

end

app/models/opcion.rb
class Opcion < ActiveRecord::Base
	mount_uploader :imagen, ImagenUploader

	belongs_to :encuesta
	after_create :default

	def default
		self.cantidad_elegida = 0
	end

	def self.sumar_voto id
		opcion = self.find(id)
		puts "Antes tenia #{opcion.cantidad_elegida}"
		nueva_cantidad = opcion.cantidad_elegida+1
		puts "Ahora tiene que tener #{nueva_cantidad}"
		if opcion.update({cantidad_elegida: nueva_cantidad})
			puts "Pero se registro con #{opcion.cantidad_elegida}"
			nueva_cantidad
		else
			puts "Hubo un error"
		end
	end

end

app/controllers/admin/categorias_controller.rb
module Admin
class CategoriasController < ApplicationController
  http_basic_authenticate_with name: ENV["LM_LOGIN"], password: ENV["LM_PASS"]
  before_action :set_categoria, only: [:show, :edit, :update, :destroy]

  # GET /categorias
  # GET /categorias.json
  def index
    @categorias = Categoria.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
  end

  # GET /categorias/new
  def new
    @categoria = Categoria.new
  end

  # GET /categorias/1/edit
  def edit
  end

  # POST /categorias
  # POST /categorias.json
  def create
    @categoria = Categoria.new(categoria_params)

    respond_to do |format|
      if @categoria.save
        format.html { redirect_to ['admin',@categoria], notice: 'Categoria was successfully created.' }
        format.json { render :show, status: :created, location: @categoria }
      else
        format.html { render :new }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @categoria.update(categoria_params)
        format.html { redirect_to ['admin', @categoria], notice: 'Categoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @categoria }
      else
        format.html { render :edit }
        format.json { render json: @categoria.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy
    @categoria.destroy
    respond_to do |format|
      format.html { redirect_to admin_categorias_url, notice: 'Categoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categoria_params
      params.require(:categoria).permit(:nombre)
    end
end
end

app/controllers/admin/encuestas_controller.rb
module Admin
class EncuestasController < ApplicationController
  http_basic_authenticate_with name: ENV["LM_LOGIN"], password: ENV["LM_PASS"]
  before_action :set_encuesta, only: [:show, :edit, :update, :destroy, :resultados]

  # GET /encuestas
  # GET /encuestas.json
  def index
    @encuestas = Encuesta.all
  end

  # GET /encuestas/1
  # GET /encuestas/1.json
  def show
  end

  # GET /encuestas/new
  def new
    @encuesta = Encuesta.new
  end

  # GET /encuestas/1/edit
  def edit
  end

  # POST /encuestas
  # POST /encuestas.json
  def create
    @encuesta = Encuesta.new(encuesta_params)

    respond_to do |format|
      if @encuesta.save
        format.html { redirect_to ['admin',@encuesta], notice: 'Encuesta was successfully created.' }
        format.json { render :show, status: :created, location: @encuesta }
      else
        format.html { render :new }
        format.json { render json: @encuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encuestas/1
  # PATCH/PUT /encuestas/1.json
  def update
    respond_to do |format|
      if @encuesta.update(encuesta_params)
        format.html { redirect_to ['admin', @encuesta], notice: 'Encuesta was successfully updated.' }
        format.json { render :show, status: :ok, location: @encuesta }
      else
        format.html { render :edit }
        format.json { render json: @encuesta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encuestas/1
  # DELETE /encuestas/1.json
  def destroy
    @encuesta.destroy
    respond_to do |format|
      format.html { redirect_to admin_encuestas_url, notice: 'Encuesta was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def votar
    suma = Opcion.sumar_voto(params[:opcion])
    render :json => suma
  end

  def resultados
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_encuesta
      @encuesta = Encuesta.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def encuesta_params
      params.require(:encuesta).permit(:nombre, :pregunta, :categoria_id, opciones_attributes: [:id, :nombre, :imagen, :cantidad_elegida, :color, :_destroy])
    end
end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	http_basic_authenticate_with name: ENV["LM_LOGIN"], password: ENV["LM_PASS"]
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_csrf_cookie_for_ng

	def set_csrf_cookie_for_ng
	  cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
	end

	protected
	def verified_request?
	    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
	  end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController

  def main
  end

  def acerca_de
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cabezal_autorizacion
		codificado = Base64.strict_encode64("#{ENV['LM_LOGIN']}:#{ENV['LM_PASS']}")
		"Basic #{codificado}"
	end
end

app/helpers/browse_helper.rb
module BrowseHelper
end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/helpers/encuestas_helper.rb
module EncuestasHelper
end

app/views/admin/categorias/_form.html.erb
<%= form_for([:admin, @categoria]) do |f| %>
  <% if @categoria.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categoria.errors.count, "error") %> prohibited this categoria from being saved:</h2>

      <ul>
      <% @categoria.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/categorias/edit.html.erb
<h1>Editing Categoria</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @categoria] %> |
<%= link_to 'Back', admin_categorias_path %>

app/views/admin/categorias/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categorias</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categorias.each do |categoria| %>
      <tr>
        <td><%= categoria.nombre %></td>
        <td><%= link_to 'Show', [:admin,categoria] %></td>
        <td><%= link_to 'Edit', edit_admin_categoria_path(categoria) %></td>
        <td><%= link_to 'Destroy', [:admin, categoria], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categoria', new_admin_categoria_path %>

app/views/admin/categorias/new.html.erb
<h1>New Categoria</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categorias_path %>

app/views/admin/categorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @categoria.nombre %>
</p>

<%= link_to 'Edit', edit_admin_categoria_path(@categoria) %> |
<%= link_to 'Back', admin_categorias_path %>

app/views/admin/encuestas/_form.html.erb
<%= form_for([:admin, @encuesta]) do |f| %>
  <% if @encuesta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@encuesta.errors.count, "error") %> prohibited this encuesta from being saved:</h2>

      <ul>
      <% @encuesta.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="input-field">
    <%= f.label :pregunta %><br>
    <%= f.text_area :pregunta, class: 'materialize-textarea' %>
  </div>
  <div class="input-field">
    <%= f.collection_select :categoria_id, Categoria.all, :id, :nombre %>
    <%= f.label :categoria %><br>
  </div>
  <h3>Opciones</h3>
    <div class="row">
    <div id="opciones">
      <%= f.fields_for :opciones do |opcion| %>
        <%= render 'opcion_fields', :f => opcion %>
      <% end %>
    </div>
  </div>
  <div class="links">
    <%= link_to_add_association 'Agregar opcion', f, :opciones, class: 'waves-effect waves-light btn' %>
  </div>
  <div class="actions">
    <%= f.submit 'Confirmar', class: 'button' %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
    $('select').material_select();
  });
</script>

app/views/admin/encuestas/_opcion_fields.html.erb
<div class="nested-fields">
	<div class="col m4">
		<div class="card">
			<%= link_to_remove_association f, class: 'waves-effect waves-light btn-floating right red' do %>
				<i class="mdi-content-clear"></i>
			<% end %>
			<div class="input-field">
				<%= f.label :nombre %>
				<%= f.text_field :nombre %>
			</div>
			<div class="input-field">
				<%= f.label :color %>
				<%= f.text_field :color %>
			</div>
			<div class="input-field">
				<%= f.label :imagen %>
				<%= f.file_field :imagen %>
			</div>
		</div>
	</div>
</div>

app/views/admin/encuestas/edit.html.erb
<h1>Editing Encuesta</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @encuesta] %> |
<%= link_to 'Back', admin_encuestas_path %>

app/views/admin/encuestas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Encuestas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Pregunta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encuestas.each do |encuesta| %>
      <tr>
        <td><%= encuesta.nombre %></td>
        <td><%= encuesta.pregunta %></td>
        <td><%= link_to 'Show', admin_encuesta_path(encuesta) %></td>
        <td><%= link_to 'Edit', edit_admin_encuesta_path(encuesta) %></td>
        <td><%= link_to 'Destroy', admin_encuesta_path(encuesta), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Encuesta', new_admin_encuesta_path %>

app/views/admin/encuestas/new.html.erb
<h1>New Encuesta</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_encuestas_path %>

app/views/admin/encuestas/show.html.erb
<p id="notice"><%= notice %></p>

<h2>  <%= @encuesta.pregunta %> </h2>

<div class="row">
<% @encuesta.opciones.each do |opcion| %>
<div class="col s3">
	<div class="card">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag opcion.imagen_url %>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= "#{opcion.nombre} - Elegido #{opcion.cantidad_elegida}" %></span>
        </div>
      </div>
  </div>
<% end %>
</div>


<%= link_to 'Edit', edit_admin_encuesta_path(@encuesta) %> |
<%= link_to 'Back', admin_encuestas_path %>

app/views/admin/index.html.erb
<h1>Administrador</h1>
<ul>
	<li><%= link_to 'Encuestas', admin_encuestas_path %></li>
	<li><%= link_to 'Categorias', admin_categorias_path %></li>
</ul>

app/views/browse/acerca_de.html.erb
<h1>Browse#acerca_de</h1>
<p>Find me in app/views/browse/acerca_de.html.erb</p>

app/views/browse/main.html.erb
<div data-ng-app="MainApp" data-ng-controller="MainCtrl" data-ng-cloak>
	<button class="waves-effect waves-light btn margen-arriba right" id="btn-categorias" data-activates="nav-categorias">
		{{categoria.nombre || 'Categorías'}}
	</button>
	<div class="ui-view-container">
		<div data-ui-view ></div>
	</div>

	<ul class="side-nav" id="nav-categorias">
		<li><h4>Categorias</h4>
			<li data-ng-repeat="categoria in categorias">
				<a data-ui-sref="categoria({id: {{categoria.id}} })">{{categoria.nombre}}</a>
			</li>
		</li>
	</ul>
</div>

<div id="modal_votado" class="modal">
	<div class="modal-content">
		<h4>Gracias por votar</h4>
		<p>Este texto esta de relleno por si se quiere usar para algo</p>
	</div>
	<div class="modal-footer">
		<a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Aceptar</a>
	</div>
</div>

<script type="text/javascript">
$( document ).ready(function() {
	$("#btn-categorias").sideNav({closeOnClick: true, edge: 'right'});
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lo Mejor de lo Mejor</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css"></link>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/js/materialize.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular-resource.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-router/0.2.15/angular-ui-router.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.16/angular-animate.min.js"></script>

  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body class="green lighten-5">
  <nav>
    <div class="nav-wrapper green">
    	<div class="container">
    		<a href="#" class="brand-logo center">Lo Mejor de lo Mejor</a>
			<ul class="right">
				
			</ul>
	    </div>
    </div>
  </nav>
<div class="container">      
	<%= yield %>
</div>

</body>
</html>